services:
  easygame-server: # Modify to use service name instead of hardcoded hostname
    build: .
    ports:
      - 8081:8080
    depends_on:
      easygame-db:
        condition: service_healthy
      easygame-cache-server:
        condition: service_healthy
  easygame-db: # Modify to use service name instead of hardcoded hostname
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your-password
      MYSQL_DATABASE: easygame
      TZ: UTC
    volumes:
      - your-mount-directory:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
  easygame-cache-server: # Modify to use service name instead of hardcoded hostname
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10